[Node]
  StartupTimeout = "{{ .Values.node.config.bridge.config.Node.StartupTimeout }}"
  ShutdownTimeout = "{{ .Values.node.config.bridge.config.Node.ShutdownTimeout }}"
[Core]
  IP = "{{ .Values.node.config.bridge.config.Core.IP }}"
  RPCPort = "{{ .Values.node.config.bridge.config.Core.RPCPort }}"
  GRPCPort = "{{ .Values.node.config.bridge.config.Core.GRPCPort }}"
[State]
  DefaultKeyName = "{{ .Values.node.config.bridge.config.State.DefaultKeyName }}"
  DefaultBackendName = "{{ .Values.node.config.bridge.config.State.DefaultBackendName }}"
[P2P]
  ListenAddresses = [{{ range $index, $element := .Values.node.config.bridge.config.P2P.ListenAddresses }}{{ if $index }}, {{ end }}"{{ $element }}"{{ end }}]
  AnnounceAddresses = {{ .Values.node.config.bridge.config.P2P.AnnounceAddresses }}
  NoAnnounceAddresses = [{{ range $index, $element := .Values.node.config.bridge.config.P2P.NoAnnounceAddresses }}{{ if $index }}, {{ end }}"{{ $element }}"{{ end }}]
  MutualPeers = {{ .Values.node.config.bridge.config.P2P.MutualPeers }}
  PeerExchange = {{ .Values.node.config.bridge.config.P2P.PeerExchange }}
  [P2P.ConnManager]
    Low = {{ printf "%.0f" .Values.node.config.bridge.config.P2P.ConnManager.Low }}
    High = {{ printf "%.0f" .Values.node.config.bridge.config.P2P.ConnManager.High }}
    GracePeriod = "{{ .Values.node.config.bridge.config.P2P.ConnManager.GracePeriod }}"
[RPC]
  Address = "{{ .Values.node.config.bridge.config.RPC.Address }}"
  Port = "{{ .Values.node.config.bridge.config.RPC.Port }}"
  SkipAuth = {{ .Values.node.config.bridge.config.RPC.SkipAuth }}
[Gateway]
  Address = "{{ .Values.node.config.bridge.config.Gateway.Address }}"
  Port = "{{ .Values.node.config.bridge.config.Gateway.Port }}"
  Enabled = {{ .Values.node.config.bridge.config.Gateway.Enabled }}
[Share]
  BlockStoreCacheSize = {{ printf "%.0f" .Values.node.config.bridge.config.Share.BlockStoreCacheSize }}
  UseShareExchange = {{ .Values.node.config.bridge.config.Share.UseShareExchange }}
  [Share.EDSStoreParams]
    RecentBlocksCacheSize = {{ printf "%.0f" .Values.node.config.bridge.config.Share.EDSStoreParams.RecentBlocksCacheSize }}
  [Share.ShrExEDSParams]
    ServerReadTimeout = "{{ .Values.node.config.bridge.config.Share.ShrExEDSParams.ServerReadTimeout }}"
    ServerWriteTimeout = "{{ .Values.node.config.bridge.config.Share.ShrExEDSParams.ServerWriteTimeout }}"
    HandleRequestTimeout = "{{ .Values.node.config.bridge.config.Share.ShrExEDSParams.HandleRequestTimeout }}"
    ConcurrencyLimit = {{ printf "%.0f" .Values.node.config.bridge.config.Share.ShrExEDSParams.ConcurrencyLimit }}
    BufferSize = {{ printf "%.0f" .Values.node.config.bridge.config.Share.ShrExEDSParams.BufferSize }}
  [Share.ShrExNDParams]
    ServerReadTimeout = "{{ .Values.node.config.bridge.config.Share.ShrExNDParams.ServerReadTimeout }}"
    ServerWriteTimeout = "{{ .Values.node.config.bridge.config.Share.ShrExNDParams.ServerWriteTimeout }}"
    HandleRequestTimeout = "{{ .Values.node.config.bridge.config.Share.ShrExNDParams.HandleRequestTimeout }}"
    ConcurrencyLimit = {{ printf "%.0f" .Values.node.config.bridge.config.Share.ShrExNDParams.ConcurrencyLimit }}
  [Share.PeerManagerParams]
    PoolValidationTimeout = "{{ .Values.node.config.bridge.config.Share.PeerManagerParams.PoolValidationTimeout }}"
    PeerCooldown = "{{ .Values.node.config.bridge.config.Share.PeerManagerParams.PeerCooldown }}"
    GcInterval = "{{ .Values.node.config.bridge.config.Share.PeerManagerParams.GcInterval }}"
    EnableBlackListing = {{ .Values.node.config.bridge.config.Share.PeerManagerParams.EnableBlackListing }}
  [Share.Discovery]
    PeersLimit = {{ printf "%.0f" .Values.node.config.bridge.config.Share.Discovery.PeersLimit }}
    AdvertiseInterval = "{{ .Values.node.config.bridge.config.Share.Discovery.AdvertiseInterval }}"
[Header]
  TrustedHash = "{{ .Values.node.config.bridge.config.Header.TrustedHash }}"
  TrustedPeers = {{ .Values.node.config.bridge.config.Header.TrustedPeers }}
  [Header.Store]
    StoreCacheSize = {{ printf "%.0f" .Values.node.config.bridge.config.Header.Store.StoreCacheSize }}
    IndexCacheSize = {{ printf "%.0f" .Values.node.config.bridge.config.Header.Store.IndexCacheSize }}
    WriteBatchSize = {{ printf "%.0f" .Values.node.config.bridge.config.Header.Store.WriteBatchSize }}
  [Header.Syncer]
    TrustingPeriod = "{{ .Values.node.config.bridge.config.Header.Syncer.TrustingPeriod }}"
  [Header.Server]
    WriteDeadline = "{{ .Values.node.config.bridge.config.Header.Server.WriteDeadline }}"
    ReadDeadline = "{{ .Values.node.config.bridge.config.Header.Server.ReadDeadline }}"
    RangeRequestTimeout = "{{ .Values.node.config.bridge.config.Header.Server.RangeRequestTimeout }}"
  [Header.Client]
    MaxHeadersPerRangeRequest = {{ printf "%.0f" .Values.node.config.bridge.config.Header.Client.MaxHeadersPerRangeRequest }}
    RangeRequestTimeout = "{{ .Values.node.config.bridge.config.Header.Client.RangeRequestTimeout }}"
[Pruner]
  EnableService = {{ .Values.node.config.bridge.config.Pruner.EnableService }}

