Node:
  StartupTimeout: 2m0s
  ShutdownTimeout: 2m0s
Core:
  IP: ""
  RPCPort: "26657"
  GRPCPort: "9090"
State:
  DefaultKeyName: my_celes_key
  DefaultBackendName: test
P2P:
  ListenAddresses:
    - /ip4/0.0.0.0/udp/2121/quic-v1/webtransport
    - /ip6/::/udp/2121/quic-v1/webtransport
    - /ip4/0.0.0.0/udp/2121/quic-v1
    - /ip6/::/udp/2121/quic-v1
    - /ip4/0.0.0.0/udp/2121/webrtc-direct
    - /ip6/::/udp/2121/webrtc-direct
    - /ip4/0.0.0.0/tcp/2121
    - /ip6/::/tcp/2121
  AnnounceAddresses: []
  NoAnnounceAddresses:
    - /ip4/127.0.0.1/udp/2121/quic-v1/webtransport
    - /ip4/0.0.0.0/udp/2121/quic-v1/webtransport
    - /ip6/::/udp/2121/quic-v1/webtransport
    - /ip4/0.0.0.0/udp/2121/quic-v1
    - /ip4/127.0.0.1/udp/2121/quic-v1
    - /ip6/::/udp/2121/quic-v1
    - /ip4/0.0.0.0/udp/2121/webrtc-direct
    - /ip4/127.0.0.1/udp/2121/webrtc-direct
    - /ip6/::/udp/2121/webrtc-direct
    - /ip4/0.0.0.0/tcp/2121
    - /ip4/127.0.0.1/tcp/2121
    - /ip6/::/tcp/2121
  MutualPeers: []
  PeerExchange: true
  ConnManager:
    Low: 800
    High: 1000
    GracePeriod: 1m0s
RPC:
  Address: localhost
  Port: "26658"
  SkipAuth: false
Gateway:
  Address: localhost
  Port: "26659"
  Enabled: false
Share:
  BlockStoreCacheSize: 128
  UseShareExchange: true
  EDSStoreParams:
    RecentBlocksCacheSize: 10
  ShrExEDSParams:
    ServerReadTimeout: 5s
    ServerWriteTimeout: 1m0s
    HandleRequestTimeout: 1m0s
    ConcurrencyLimit: 10
    BufferSize: 32768
  ShrExNDParams:
    ServerReadTimeout: 5s
    ServerWriteTimeout: 1m0s
    HandleRequestTimeout: 1m0s
    ConcurrencyLimit: 10
  PeerManagerParams:
    PoolValidationTimeout: 2m0s
    PeerCooldown: 3s
    GcInterval: 30s
    EnableBlackListing: false
  Discovery:
    PeersLimit: 5
    AdvertiseInterval: 1h0m0s
Header:
  TrustedHash: ""
  TrustedPeers: []
  Store:
    StoreCacheSize: 4096
    IndexCacheSize: 16384
    WriteBatchSize: 2048
  Syncer:
    TrustingPeriod: 336h0m0s
  Server:
    WriteDeadline: 8s
    ReadDeadline: 1m0s
    RangeRequestTimeout: 10s
  Client:
    MaxHeadersPerRangeRequest: 64
    RangeRequestTimeout: 8s
DASer:
  SamplingRange: 100
  ConcurrencyLimit: 6
  BackgroundStoreInterval: 10m0s
  SampleFrom: 1
  SampleTimeout: 2m0s
Pruner:
  EnableService: false
